{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMGKSPmW8wrljcY6K3JBIOp",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/bugraaksu1/DS570_Project/blob/Development_Workspace/preprocessing.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 275
        },
        "id": "LsqjoqCYwzGj",
        "outputId": "aed459c3-1946-4256-ae79-0c66ac744e4e"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[INFO] Fetching data from: https://raw.githubusercontent.com/bugraaksu1/DS570_Project/main/data/Finalized_Dataset.csv\n",
            "[INFO] Splitting dataset chronologically (target: Signal_Y)...\n",
            "[SUCCESS] Split complete.\n",
            "Train set: 83872 rows | Test set: 20968 rows\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "   TimeStamp  Signal_X1  Signal_X2  Signal_X3  Signal_X4  Signal_X5  \\\n",
              "0      0.015     0.3742     0.5452     0.5006     0.8425     0.1429   \n",
              "1      0.025     0.3743     0.5452     0.5017     0.8425     0.1714   \n",
              "2      0.035     0.3746     0.5452     0.5029     0.8420     0.1714   \n",
              "3      0.045     0.3747     0.5437     0.5032     0.8420     0.1714   \n",
              "4      0.055     0.3748     0.5424     0.5035     0.8420     0.2000   \n",
              "\n",
              "   Signal_X6  Signal_X7  Signal_X8  Signal_X9  Signal_X10  Signal_X11  \n",
              "0     0.7508        0.0     0.0435        0.0         0.0         0.0  \n",
              "1     0.7508        0.0     0.0435        0.0         0.0         0.0  \n",
              "2     0.7508        0.0     0.0435        0.0         0.0         0.0  \n",
              "3     0.7508        0.0     0.0435        0.0         0.0         0.0  \n",
              "4     0.7508        0.0     0.0435        0.0         0.0         0.0  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-935563f5-9686-44ad-8722-5e46bf981e18\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>TimeStamp</th>\n",
              "      <th>Signal_X1</th>\n",
              "      <th>Signal_X2</th>\n",
              "      <th>Signal_X3</th>\n",
              "      <th>Signal_X4</th>\n",
              "      <th>Signal_X5</th>\n",
              "      <th>Signal_X6</th>\n",
              "      <th>Signal_X7</th>\n",
              "      <th>Signal_X8</th>\n",
              "      <th>Signal_X9</th>\n",
              "      <th>Signal_X10</th>\n",
              "      <th>Signal_X11</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>0.015</td>\n",
              "      <td>0.3742</td>\n",
              "      <td>0.5452</td>\n",
              "      <td>0.5006</td>\n",
              "      <td>0.8425</td>\n",
              "      <td>0.1429</td>\n",
              "      <td>0.7508</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0435</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>0.025</td>\n",
              "      <td>0.3743</td>\n",
              "      <td>0.5452</td>\n",
              "      <td>0.5017</td>\n",
              "      <td>0.8425</td>\n",
              "      <td>0.1714</td>\n",
              "      <td>0.7508</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0435</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>0.035</td>\n",
              "      <td>0.3746</td>\n",
              "      <td>0.5452</td>\n",
              "      <td>0.5029</td>\n",
              "      <td>0.8420</td>\n",
              "      <td>0.1714</td>\n",
              "      <td>0.7508</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0435</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>0.045</td>\n",
              "      <td>0.3747</td>\n",
              "      <td>0.5437</td>\n",
              "      <td>0.5032</td>\n",
              "      <td>0.8420</td>\n",
              "      <td>0.1714</td>\n",
              "      <td>0.7508</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0435</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>0.055</td>\n",
              "      <td>0.3748</td>\n",
              "      <td>0.5424</td>\n",
              "      <td>0.5035</td>\n",
              "      <td>0.8420</td>\n",
              "      <td>0.2000</td>\n",
              "      <td>0.7508</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0435</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-935563f5-9686-44ad-8722-5e46bf981e18')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-935563f5-9686-44ad-8722-5e46bf981e18 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-935563f5-9686-44ad-8722-5e46bf981e18');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"        print(f\\\"[ERROR] Failed to process data: {error}\\\")\",\n  \"rows\": 5,\n  \"fields\": [\n    {\n      \"column\": \"TimeStamp\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.015811388300841896,\n        \"min\": 0.015,\n        \"max\": 0.055,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          0.025,\n          0.055,\n          0.035\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X1\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.00025884358211089933,\n        \"min\": 0.3742,\n        \"max\": 0.3748,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          0.3743,\n          0.3748,\n          0.3746\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X2\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.0012641202474448553,\n        \"min\": 0.5424,\n        \"max\": 0.5452,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          0.5452,\n          0.5437,\n          0.5424\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X3\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.0012070625501604771,\n        \"min\": 0.5006,\n        \"max\": 0.5035,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          0.5017,\n          0.5035,\n          0.5029\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X4\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.00027386127875261374,\n        \"min\": 0.842,\n        \"max\": 0.8425,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0.842,\n          0.8425\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X5\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.02018791717835201,\n        \"min\": 0.1429,\n        \"max\": 0.2,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          0.1429,\n          0.1714\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X6\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.0,\n        \"min\": 0.7508,\n        \"max\": 0.7508,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0.7508\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X7\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.0,\n        \"min\": 0.0,\n        \"max\": 0.0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X8\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.0,\n        \"min\": 0.0435,\n        \"max\": 0.0435,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0.0435\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X9\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.0,\n        \"min\": 0.0,\n        \"max\": 0.0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X10\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.0,\n        \"min\": 0.0,\n        \"max\": 0.0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Signal_X11\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.0,\n        \"min\": 0.0,\n        \"max\": 0.0,\n        \"num_unique_values\": 1,\n        \"samples\": [\n          0.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ],
      "source": [
        "import pandas as pd\n",
        "from sklearn.model_selection import train_test_split\n",
        "\n",
        "def prepare_and_split_data(df, target_col='Signal_Y', test_size=0.2):\n",
        "    \"\"\"\n",
        "    Splits the dataframe chronologically to maintain time-series integrity\n",
        "    and prevent data leakage.\n",
        "    \"\"\"\n",
        "    print(f\"[INFO] Splitting dataset chronologically (target: {target_col})...\")\n",
        "\n",
        "    if target_col not in df.columns:\n",
        "        available = df.columns.tolist()\n",
        "        raise KeyError(f\"Target column '{target_col}' not found. Available columns: {available}\")\n",
        "\n",
        "    X = df.drop(columns=[target_col])\n",
        "    y = df[target_col]\n",
        "\n",
        "    # shuffle=False is critical for time-series data to preserve the order\n",
        "    X_train, X_test, y_train, y_test = train_test_split(\n",
        "        X, y, test_size=test_size, shuffle=False\n",
        "    )\n",
        "\n",
        "    print(f\"[SUCCESS] Split complete.\")\n",
        "    print(f\"Train set: {X_train.shape[0]} rows | Test set: {X_test.shape[0]} rows\")\n",
        "\n",
        "    return X_train, X_test, y_train, y_test\n",
        "\n",
        "def load_remote_data(url):\n",
        "    \"\"\"\n",
        "    Loads the dataset from GitHub, handling specific CSV formatting issues.\n",
        "    \"\"\"\n",
        "    print(f\"[INFO] Fetching data from: {url}\")\n",
        "\n",
        "    # The dataset uses ';' as separator and ',' for decimals\n",
        "    df = pd.read_csv(url, sep=';', decimal=',')\n",
        "\n",
        "    # Clean up any trailing whitespace in column names\n",
        "    df.columns = df.columns.str.strip()\n",
        "\n",
        "    return df\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    DATA_URL = \"https://raw.githubusercontent.com/bugraaksu1/DS570_Project/main/data/Finalized_Dataset.csv\"\n",
        "\n",
        "    try:\n",
        "        raw_df = load_remote_data(DATA_URL)\n",
        "        X_train, X_test, y_train, y_test = prepare_and_split_data(raw_df)\n",
        "\n",
        "        # Quick preview\n",
        "        display(X_train.head())\n",
        "\n",
        "    except Exception as error:\n",
        "        print(f\"[ERROR] Failed to process data: {error}\")"
      ]
    }
  ]
}